lvgl:
  page_wrap: true
  theme:
    obj:
      scrollbar_mode: "OFF"    
      width: 100%
      height: 100%    
      border_width: 0
      pad_all: 0
      radius: 0
      scrollable: false      
      bg_opa: TRANSP
      outline_width: 1
      outline_color: red
    label:
      scrollbar_mode: "OFF"
      border_width: 0
      scrollable: false
      text_font: $text_font
      text_color: $label_off_color
      outline_width: 1
      outline_color: red
    image:
      scrollbar_mode: "OFF"
      border_width: 0
      scrollable: false
      outline_width: 1
      outline_color: red
    button:
      scrollbar_mode: "OFF"
      width: 100%
      height: 100%      
      border_width: 0
      radius: 25
      pad_all: 10
      shadow_width: 0 # Bug? - This is required even though the default is supposed to be 0.
      checkable: false
      press_lock: false
      scroll_on_focus: true      
      bg_opa: cover
      bg_color: $button_off_color
      outline_width: 1
      outline_color: red

  style_definitions:
    - id: page_style
      scrollbar_mode: "OFF"
      bg_color: black
      bg_opa: cover
      pad_all: 1

    - id: time_style
      scrollbar_mode: "OFF"
      text_font: $text_font
      text_color: $label_on_color
      align: center
      outline_width: 1
      outline_color: red       

select:
  - platform: template
    name: "Current Theme"
    id: current_theme
    icon: mdi:theme-light-dark
    optimistic: true
    options:
      - Dark
      - Light
    initial_option: Dark
    on_value:
      then:
        - if:
            condition:
              - lambda: 'return id(current_theme).current_option() == "Dark";'
            then:
              - lvgl.style.update:
                  id: page_style
                  bg_color: black
                  text_color: white
              - lvgl.widget.redraw
        - if:
            condition:
              - lambda: 'return id(current_theme).current_option() == "Light";'
            then:
              - lvgl.style.update:
                  id: page_style
                  bg_color: white
                  text_color: black
              - lvgl.widget.redraw